import type { Abi } from 'viem';

export const tokenVestingAbi = [
	{
		type: 'constructor',
		inputs: [
			{
				name: '_vestingToken',
				type: 'address',
				internalType: 'address',
			},
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'VESTING_TOKEN',
		inputs: [],
		outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'addBeneficiary',
		inputs: [
			{ name: 'beneficiary', type: 'address', internalType: 'address' },
			{
				name: 'totalAllocation',
				type: 'uint256',
				internalType: 'uint256',
			},
			{ name: 'startTime', type: 'uint256', internalType: 'uint256' },
			{
				name: 'cliffDuration',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'vestingDuration',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'beneficiaries',
		inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		outputs: [{ name: '', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'claimVestedTokens',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'getBeneficiariesLength',
		inputs: [],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getClaimableAmount',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getRemainingAllocation',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getVestedAmount',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getVestingSchedule',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [
			{
				name: '',
				type: 'tuple',
				internalType: 'struct TokenVesting.VestingSchedule',
				components: [
					{
						name: 'totalAllocation',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'startTime',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'cliffDuration',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'vestingDuration',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'amountClaimed',
						type: 'uint256',
						internalType: 'uint256',
					},
					{ name: 'revoked', type: 'bool', internalType: 'bool' },
					{
						name: 'unvestedTokensReclaimed',
						type: 'bool',
						internalType: 'bool',
					},
					{
						name: 'amountVestedAtRevocation',
						type: 'uint256',
						internalType: 'uint256',
					},
				],
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'hasVestingSchedule',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'owner',
		inputs: [],
		outputs: [{ name: '', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'pause',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'paused',
		inputs: [],
		outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'reclaimUnvestedTokens',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'renounceOwnership',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'revokeSchedule',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'totalOutstandingAllocation',
		inputs: [],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'transferOwnership',
		inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'unpause',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'vestingSchedules',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
		outputs: [
			{
				name: 'totalAllocation',
				type: 'uint256',
				internalType: 'uint256',
			},
			{ name: 'startTime', type: 'uint256', internalType: 'uint256' },
			{
				name: 'cliffDuration',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'vestingDuration',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountClaimed',
				type: 'uint256',
				internalType: 'uint256',
			},
			{ name: 'revoked', type: 'bool', internalType: 'bool' },
			{
				name: 'unvestedTokensReclaimed',
				type: 'bool',
				internalType: 'bool',
			},
			{
				name: 'amountVestedAtRevocation',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'withdrawExcessTokens',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'event',
		name: 'BeneficiaryAdded',
		inputs: [
			{
				name: 'beneficiary',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'totalAllocation',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'startTime',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'cliffDuration',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'vestingDuration',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'BeneficiaryVestingScheduleRevoked',
		inputs: [
			{
				name: 'beneficiary',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'amountVestedAtRevocation',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'ExcessTokensWithdrawn',
		inputs: [
			{
				name: 'excessWithdrawn',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OwnershipTransferred',
		inputs: [
			{
				name: 'previousOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'newOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Paused',
		inputs: [
			{
				name: 'account',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'TokensClaimed',
		inputs: [
			{
				name: 'beneficiary',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'tokenAmountClaimed',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Unpaused',
		inputs: [
			{
				name: 'account',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'UnvestedTokensReclaimed',
		inputs: [
			{
				name: 'beneficiary',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'amountReclaimed',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{ type: 'error', name: 'EnforcedPause', inputs: [] },
	{ type: 'error', name: 'ExpectedPause', inputs: [] },
	{
		type: 'error',
		name: 'OwnableInvalidOwner',
		inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
	},
	{
		type: 'error',
		name: 'OwnableUnauthorizedAccount',
		inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
	},
	{
		type: 'error',
		name: 'SafeERC20FailedOperation',
		inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
	},
	{
		type: 'error',
		name: 'TokenVesting__BeneficiaryAlreadyExists',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
	},
	{
		type: 'error',
		name: 'TokenVesting__BeneficiaryDoesNotExist',
		inputs: [{ name: 'beneficiary', type: 'address', internalType: 'address' }],
	},
	{
		type: 'error',
		name: 'TokenVesting__CliffDurationIsGreaterThanVestingDuration',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TokenVesting__ContractUnderfunded',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TokenVesting__InsufficientFunding',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TokenVesting__InvalidAllocationAmount',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TokenVesting__InvalidBeneficiaryAddress',
		inputs: [],
	},
	{ type: 'error', name: 'TokenVesting__InvalidStartTime', inputs: [] },
	{ type: 'error', name: 'TokenVesting__InvalidToken', inputs: [] },
	{
		type: 'error',
		name: 'TokenVesting__InvalidVestingDuration',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TokenVesting__NoExcessTokensToWithdraw',
		inputs: [],
	},
	{ type: 'error', name: 'TokenVesting__NothingToReclaim', inputs: [] },
	{
		type: 'error',
		name: 'TokenVesting__ScheduleAlreadyRevoked',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TokenVesting__ScheduleNotRevoked',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TokenVesting__UnvestedTokensAlreadyReclaimed',
		inputs: [],
	},
	{ type: 'error', name: 'TokenVesting__ZeroTokensToClaim', inputs: [] },
] as const satisfies Abi;
